# Generated by Django 5.1.7 on 2025-03-29 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='VendorProduct',
            new_name='Products',
        ),
    ]
