# Generated by Django 5.1.7 on 2025-03-29 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_product_delete_products'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
