# Generated by Django 5.1.7 on 2025-03-29 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_product'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
