# Generated by Django 5.1.7 on 2025-04-01 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0007_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='service_provider',
        ),
        migrations.DeleteModel(
            name='Booking',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
