# Generated by Django 5.1.7 on 2025-04-01 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0008_remove_product_service_provider_delete_booking_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceprovider',
            name='category_type',
            field=models.CharField(default='default_category', max_length=100),
        ),
    ]
