# Generated by Django 5.1.7 on 2025-04-03 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0011_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceprovider',
            name='service_type',
            field=models.CharField(default='both', max_length=100),
        ),
    ]
