# Generated by Django 5.1.7 on 2025-04-03 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0012_serviceprovider_service_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='service_type',
            field=models.CharField(default='home_delivery', max_length=100),
        ),
    ]
