# Generated by Django 5.1.7 on 2025-04-03 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0014_alter_booking_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
