# Generated by Django 5.1.7 on 2025-04-04 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0017_services'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Services',
        ),
    ]
