# Generated by Django 5.1.7 on 2025-04-04 08:39

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0019_services'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='services',
            name='booking_date',
        ),
        migrations.RemoveField(
            model_name='services',
            name='completion_date',
        ),
        migrations.RemoveField(
            model_name='services',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='services',
            name='status',
        ),
        migrations.CreateModel(
            name='Service_Based_Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('service_type', models.CharField(choices=[('pick_up', 'Pick Up'), ('home_delivery', 'Home Delivery'), ('in_store', 'In-Store Service'), ('home_service', 'Home Service')], max_length=50)),
                ('booking_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Confirmed', 'Confirmed'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Pending', max_length=20)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.customerinfo')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.services')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.serviceprovider')),
            ],
        ),
    ]
