# Generated by Django 5.1.7 on 2025-04-04 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0020_remove_services_booking_date_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Service_Based_Booking',
        ),
    ]
