# Generated by Django 5.1.7 on 2025-04-04 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0022_service_based_booking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service_based_booking',
            name='quantity',
        ),
    ]
