# Generated by Django 5.1.7 on 2025-04-04 20:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0023_remove_service_based_booking_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='service_based_booking',
            name='booking_time',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 4, 4, 20, 2, 27, 810823, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
