# Generated by Django 5.1.7 on 2025-04-11 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0024_service_based_booking_booking_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerinfo',
            name='working_hours',
        ),
        migrations.AddField(
            model_name='serviceprovider',
            name='working_hours',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
