# Generated by Django 5.1.7 on 2025-04-14 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0026_cart_cartitem_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='action_type',
            field=models.CharField(choices=[('booking', 'Booking'), ('status_update', 'Status Update'), ('payment', 'Payment'), ('general', 'General')], default='general', max_length=20),
        ),
        migrations.AddField(
            model_name='notification',
            name='is_responded',
            field=models.BooleanField(default=False),
        ),
    ]
