# Generated by Django 5.1.7 on 2025-04-14 08:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0027_notification_action_type_notification_is_responded'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopitem',
            name='vendor',
            field=models.ForeignKey(db_column='vendor_id', on_delete=django.db.models.deletion.CASCADE, to='services.serviceprovider'),
        ),
    ]
