# Generated by Django 5.1.7 on 2025-04-14 08:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0028_alter_shopitem_vendor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopitem',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.serviceprovider'),
        ),
    ]
