# Generated by Django 5.1.7 on 2025-04-15 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0029_alter_shopitem_vendor'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GeoCluster',
        ),
    ]
