# Generated by Django 5.1.7 on 2025-04-16 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0031_order_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceprovider',
            name='car_type',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
