# Generated by Django 5.1.7 on 2025-04-16 18:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0032_serviceprovider_car_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serviceprovider',
            name='category',
        ),
        migrations.AddField(
            model_name='customuser',
            name='category',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
