# Generated by Django 5.1.7 on 2025-04-21 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0033_remove_serviceprovider_category_customuser_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='service_type',
            field=models.CharField(choices=[('pick_up', 'Pick Up'), ('home_delivery', 'Home Delivery')], default='home_delivery', max_length=20),
        ),
    ]
