# Generated by Django 5.1.7 on 2025-04-21 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0034_order_service_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='service_type',
        ),
    ]
