# Generated by Django 5.1.7 on 2025-04-21 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0035_remove_order_service_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='services',
            name='is_available',
        ),
        migrations.RemoveField(
            model_name='services',
            name='location',
        ),
    ]
