# Generated by Django 5.1.7 on 2025-04-21 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0036_remove_services_is_available_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
    ]
