# Generated by Django 4.2.7 on 2025-04-21 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0038_remove_serviceprovider_car_type_rideservices_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rideserviceprovider',
            name='user',
        ),
        migrations.RemoveField(
            model_name='rideservices',
            name='vendor',
        ),
        migrations.AddField(
            model_name='serviceprovider',
            name='car_type',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Ride_Service_Booking',
        ),
        migrations.DeleteModel(
            name='RideServiceProvider',
        ),
        migrations.DeleteModel(
            name='RideServices',
        ),
    ]
