# Generated by Django 4.2.7 on 2025-04-21 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0039_remove_rideserviceprovider_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceprovider',
            name='category_type',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
