# Generated by Django 4.2.7 on 2025-04-21 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0040_alter_serviceprovider_category_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='delivery_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='pickup_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='booking',
            name='service_type',
            field=models.CharField(choices=[('pick_up', 'Pick Up'), ('home_delivery', 'Home Delivery')], default='home_delivery', max_length=20),
        ),
    ]
