# Generated by Django 4.2.7 on 2025-04-21 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0041_booking_delivery_time_booking_pickup_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='order_details',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='action_type',
            field=models.CharField(choices=[('booking', 'Booking'), ('status_update', 'Status Update'), ('payment', 'Payment'), ('general', 'General'), ('order_confirmation', 'Order Confirmation')], default='general', max_length=20),
        ),
    ]
