# Generated by Django 4.2.7 on 2025-04-21 16:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0042_notification_order_details_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='item',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='quantity',
        ),
        migrations.CreateModel(
            name='BookingItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='services.booking')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.shopitem')),
            ],
        ),
    ]
