# Generated by Django 4.2.7 on 2025-04-21 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0044_bulkorder_bulkorderitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bulkorderitem',
            name='bulk_order',
        ),
        migrations.RemoveField(
            model_name='bulkorderitem',
            name='item',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='order_details',
        ),
        migrations.AlterField(
            model_name='notification',
            name='action_type',
            field=models.CharField(choices=[('booking', 'Booking'), ('status_update', 'Status Update'), ('payment', 'Payment'), ('general', 'General')], default='general', max_length=20),
        ),
        migrations.DeleteModel(
            name='BulkOrder',
        ),
        migrations.DeleteModel(
            name='BulkOrderItem',
        ),
    ]
