# Generated by Django 4.2.7 on 2025-04-22 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0046_service_based_booking_distance_km_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service_based_booking',
            name='vehicle_type',
        ),
    ]
