# Generated by Django 4.2.7 on 2025-04-22 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0048_service_based_booking_dropoff_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service_based_booking',
            name='complete_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='service_based_booking',
            name='delivered_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ] 