# Generated by Django 4.2.7 on 2025-04-23 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0049_add_complete_delivered_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service_based_booking',
            name='dropoff_city',
        ),
        migrations.RemoveField(
            model_name='service_based_booking',
            name='dropoff_pincode',
        ),
        migrations.RemoveField(
            model_name='service_based_booking',
            name='dropoff_street',
        ),
        migrations.RemoveField(
            model_name='service_based_booking',
            name='pickup_city',
        ),
        migrations.RemoveField(
            model_name='service_based_booking',
            name='pickup_pincode',
        ),
        migrations.RemoveField(
            model_name='service_based_booking',
            name='pickup_street',
        ),
        migrations.RemoveField(
            model_name='service_based_booking',
            name='vehicle_type',
        ),
        migrations.AddField(
            model_name='booking',
            name='payment_method',
            field=models.CharField(choices=[('credit_card', 'Credit Card'), ('debit_card', 'Debit Card'), ('upi', 'UPI'), ('net_banking', 'Net Banking'), ('wallet', 'Digital Wallet'), ('cod', 'Cash on Delivery')], default='cod', max_length=20),
        ),
        migrations.AddField(
            model_name='booking',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='service_based_booking',
            name='payment_method',
            field=models.CharField(choices=[('credit_card', 'Credit Card'), ('debit_card', 'Debit Card'), ('upi', 'UPI'), ('net_banking', 'Net Banking'), ('wallet', 'Digital Wallet'), ('cod', 'Cash on Delivery')], default='cod', max_length=20),
        ),
        migrations.AddField(
            model_name='service_based_booking',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='service_based_booking',
            name='distance_km',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
