# Generated by Django 4.2.7 on 2025-04-23 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0050_remove_service_based_booking_dropoff_city_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='item',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='order',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='payment_method',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='payment_status',
        ),
        migrations.RemoveField(
            model_name='service_based_booking',
            name='payment_method',
        ),
        migrations.RemoveField(
            model_name='service_based_booking',
            name='payment_status',
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('upi', 'UPI'), ('cod', 'Cash on Delivery')], max_length=20),
        ),
        migrations.AlterField(
            model_name='service_based_booking',
            name='distance_km',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
    ]
