# Generated by Django 4.2.7 on 2025-04-23 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0053_service_based_booking_payment_method_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceprovider',
            name='upi_qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='upi_qr_codes/'),
        ),
    ]
