# Generated by Django 4.2.7 on 2025-04-25 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0057_booking_complete_time_booking_delivered_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='complete_time',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='delivered_time',
        ),
    ]
