# Generated by Django 4.2.7 on 2025-04-25 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0058_remove_booking_complete_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='distance_km',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='dropoff_latitude',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='dropoff_location',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='dropoff_longitude',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='pickup_latitude',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='pickup_location',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='pickup_longitude',
        ),
    ]
