# Generated by Django 4.2.7 on 2025-04-27 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0060_booking_distance_km_booking_dropoff_latitude_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DemandForecast',
        ),
        migrations.RemoveField(
            model_name='review',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='review',
            name='provider',
        ),
        migrations.AlterModelOptions(
            name='payment',
            options={},
        ),
        migrations.RemoveField(
            model_name='booking',
            name='distance_km',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='dropoff_latitude',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='dropoff_location',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='dropoff_longitude',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='pickup_latitude',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='pickup_location',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='pickup_longitude',
        ),
        migrations.DeleteModel(
            name='Report',
        ),
        migrations.DeleteModel(
            name='Review',
        ),
    ]
