# Generated by Django 4.2.7 on 2025-04-28 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0061_delete_demandforecast_remove_review_customer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service_based_booking',
            name='delivered_time',
        ),
        migrations.RemoveField(
            model_name='serviceprovider',
            name='car_type',
        ),
    ]
